### ISSUE TITLE
Tilgangsnivå for datasett avviker fra EUs definisjoner

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/veileder-beskrivelse-av-datasett#12]
Se https://github.com/Informasjonsforvaltning/dcat-ap-no/issues/418

**Comment by oystein-asnes** [comment]
Ny omforent "fornorsking" av access-rights:

|Preferred English term|English definition with usage note                                                                                                                                                                                                                                |Anbefalt norsk term      |Norsk definisjon med merknad                                                                                                                                                                                                                                                                           |Eksempler på typer data                                                                                                                                                       |
|----------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|public                |Publicly accessible by everyone.  Usage note: Permissible obstacles include registration and request for API keys, as long as anyone can request such registration and/or API keys.                                                                               |allmenn tilgang          |tilgang som hvem som helst kan få Merknad: Tillatte hindringer inkluderer brukerregistrering og forespørsel om API-nøkler, så lenge alle kan få slik registrering og/eller API-nøkler.                                                                                                                 |<alt som ikke er de to andre kategoriene> Åpne data Data med allmenn tilgang som har bruksrestriksjoner (kun ikke-kommersiell bruk, del på samme vilkår, ingen bearbeiding mv)|
|non-public            |Not publicly accessible for privacy, security or other reasons.  Usage note: This category may include resources that contain sensitive or personal information.                                                                                                  |ikke-allmenn tilgang     |tilgang som ikke hvem som helst kan få som følge av lovregulerte begrensninger knyttet til sikkerhet, personvern eller lignende Merknad: Denne kategorien inkluderer tilgang til ressurser som inneholder sensitive data eller personopplysninger.                                                     |Alminnelige personoppl. Sensitive personoppl. Taushetsbelagte data. Rikets sikkerhet.                                                                                         |
|restricted            |Only available under certain conditions.  Usage note: This category may include resources that require payment, resources shared under non-disclosure agreements, resources for which the publisher or owner has not yet decided if they can be publicly released.|betinget tilgang         |tilgang som kun kan fås under visse betingelser bestemt av eieren eller tilbyderen Merknad 1: Eksempler på betingelser kan være betaling eller å inngå fortrolighetsavtale. Merknad 2: Kategorien inkluderer også tilgang som ennå ikke er kategorisert som allmenn tilgang eller ikke-allmenn tilgang.|Forretningshemmeligheter Opphavsrett. Tilgang som krever ekskluderende medlemskap. Avgiftsbelagte data                                                                        |

**Comment by KjerstiSteien** [comment]
@jimjyang Er det slik at veilederen ikke forvaltes lenger? Kan vi da lukke sakene som ligger i dette repoet?

**Comment by jimjyang** [comment]
Forslaget til å utfase denne veilederen er på høring (ifm. høring på DCAT-AP-NO). Det er med andre ord ikke avgjort ennå.

**Comment by jimjyang** [comment]
Veilederen utgår og vil derfor ikke bli vedlikeholdt (inkl. kjente feil/mangler). Lukkes.
