### ISSUE TITLE
Publiserer nåværende versjon av veilederen til /v1

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/veileder-beskrivelse-av-datasett#3]
Nåværende versjon av veilederen https://informasjonsforvaltning.github.io/dcat-ap-no-veileder/ skal tas vare på og publiseres som https://informasjonsforvaltning.github.io/dcat-ap-no-veileder/v1. 

VÆR OBS på at siste leddet i den nåværende URLen (`dcat-ap-no-veileder` ) ikke er samme som repo-navnet (`dcat-ap-no-veileder`). Vil dette skape krøll for senere publisering (av v2) til data.norge.no?

**Comment by jimjyang** [comment]
Repo-navnet er endret etter at jeg la inn Issuet. Det er nå samsvar.

**Comment by stigbd** [comment]
Så dermed gjelder ikkje følgande lenger:

> Nåværende versjon av veilederen https://informasjonsforvaltning.github.io/dcat-ap-no-veileder/ skal tas vare på og publiseres som https://informasjonsforvaltning.github.io/dcat-ap-no-veileder/v1.

Skal det vere som følger?
Nåværende versjon av veilederen https://data.norge.no/guide/veileder-beskrivelse-av-datasett/ skal tas vare på og publiseres som https://data.norge.no/guide/veileder-beskrivelse-av-datasett/v1

**Comment by jimjyang** [comment]
> Skal det vere som følger?
> Nåværende versjon av veilederen https://data.norge.no/guide/veileder-beskrivelse-av-datasett/ skal tas vare på og publiseres som https://data.norge.no/guide/veileder-beskrivelse-av-datasett/v1

Ja.

**Comment by stigbd** [comment]
Då blir det som følger med hensyn på brancher og publisering:
`develop` -> https://informasjonsforvaltning.github.io/veileder-beskrivelse-av-datasett/
`master` renames til `v1` -> https://data.norge.no/guide/veileder-beskrivelse-av-datasett/v1
ny branch `v2` vil bli lagd -> https://data.norge.no/guide/veileder-beskrivelse-av-datasett/v2

Og
https://data.norge.no/guide/veileder-beskrivelse-av-datasett/ redirecter til https://data.norge.no/guide/veileder-beskrivelse-av-datasett/v2

**Comment by stigbd** [comment]
Då skal dette vere i orden.

Merk: at vi hadde ein tag `v1` som heitte det same som ny branch `v1` skapte ein heil del trøbbel. Eg måtte slette tag `v1`.

Fint om @jimjyang verifiserer at ting ser bra ut.

**Comment by jimjyang** [comment]
> Fint om @jimjyang verifiserer at ting ser bra ut.

https://data.norge.no/guide/veileder-beskrivelse-av-datasett/v1 ser bra ut! 

> Og
> https://data.norge.no/guide/veileder-beskrivelse-av-datasett/ redirecter til https://data.norge.no/guide/veileder-beskrivelse-av-datasett/v2

Når den er ferdig skrevet, skal v2 være den gjeldende versjon og gjeldende versjon skal være på https://data.norge.no/guide/veileder-beskrivelse-av-datasett/. Derfor ikke redirect til /v2 (selv om, og fint at, det finnes en /v2).

**Comment by stigbd** [comment]
Ok, anser denne som løst. Oppsummering:
develop -> https://informasjonsforvaltning.github.io/veileder-beskrivelse-av-datasett/
master renames til v1 -> https://data.norge.no/guide/veileder-beskrivelse-av-datasett/v1
ny branch v2 -> https://data.norge.no/guide/veileder-beskrivelse-av-datasett/

**Comment by jimjyang** [comment]
Fint! Lukkes.
