### ISSUE TITLE
[publisering] PDF-filnavnet bør gjenspeile veilederens navn

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/veileder-beskrivelse-av-datasett#8]
Navnet til PDF-filen som kan lastes ned er nå "document.pdf". 

Ønsker å ha et filnavn som gjenspeile veilederens navn, f.eks. repo-navnet (som også brukes i URLen til den gjeldende versjonen på data.norge.no).

**Comment by stigbd** [comment]
Fiksa i 1acbf131212a4f801a5a8a72ad1cedb6bb0aaa93

**Comment by jimjyang** [comment]
Fiksa
