### ISSUE TITLE
Info om korleis angi namn på lenke til relatert ressurs på eit datasett

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/veileder-beskrivelse-av-datasett#9]
Bør vere info om korleis dette bør gjerast, gjerne med eit eksempel.
For ein relatert ressurs vil ein typisk både ha lenke og namn på lenka.

**Comment by jimjyang** [comment]
Løst, se under [Datasett - refererer til](https://data.norge.no/guide/veileder-beskrivelse-av-datasett/#datasett-referererTil). 

Lukkes.
